version: '3.8'

services:
  app:
    build: .
    image: onlinebookstore:latest
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookstoredb
    ports:
      - "5432:5432"
